# Generated by Django 4.0.4 on 2022-05-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
