# Generated by Django 4.0.4 on 2022-05-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqest', '0002_requestbook_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
