# Generated by Django 4.0.4 on 2022-05-24 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqest', '0003_requestbook_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
