# Generated by Django 4.0.4 on 2022-06-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqest', '0004_requestbook_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbook',
            name='approve_return',
            field=models.BooleanField(default=False),
        ),
    ]
