# Generated by Django 4.0.4 on 2022-06-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reqest', '0005_requestbook_approve_return'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestbook',
            options={'ordering': ('is_approved',)},
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='approval',
            new_name='is_approved',
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='approve_return',
            new_name='is_approved_return',
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='request',
            new_name='is_requested',
        ),
        migrations.RenameField(
            model_name='requestbook',
            old_name='returned',
            new_name='is_returned',
        ),
    ]
