# Generated by Django 4.0.4 on 2022-05-19 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_users_email_address_alter_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_super_teacher',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_teacher',
        ),
    ]
