# Generated by Django 4.0.4 on 2022-06-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0006_alter_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='Email_Address',
        ),
        migrations.AddField(
            model_name='users',
            name='email_address',
            field=models.EmailField(blank=True, default=None, max_length=200, unique=True, verbose_name='email'),
        ),
    ]
