# Generated by Django 4.0.4 on 2022-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0010_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email_address',
            field=models.EmailField(max_length=200, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
