# Generated by Django 4.0.4 on 2022-06-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0013_alter_users_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
