# Generated by Django 4.0.4 on 2022-06-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0014_generatedpasswords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatedpasswords',
            old_name='password',
            new_name='generated_passwords',
        ),
    ]
