# Generated by Django 4.0.4 on 2022-06-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0015_rename_password_generatedpasswords_generated_passwords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatedpasswords',
            options={'ordering': ('password',)},
        ),
        migrations.RenameField(
            model_name='generatedpasswords',
            old_name='generated_passwords',
            new_name='password',
        ),
    ]
